export const Users = [
    {
        id: 1,
        profilePicture: "person/1.jpg",
        username: "jalal uddin",
    },
    {
        id: 2,
        profilePicture: "person/2.jpg",
        username: "habibur rahman",
    },
    {
        id: 3,
        profilePicture: "person/3.png",
        username: "khalil ahmed",
    },
    {
        id: 4,
        profilePicture:"person/4.jpg",
        username: "reja sani ",
    },
    {
        id: 5,
        profilePicture: "person/5.jpg",
        username: "akbar ali",
    },
    {
        id: 6,
        profilePicture: "person/shaad.jpg",
        username: "marufuzzaman",
    },
    {
        id: 7,
        profilePicture: "person/7.jpg",
        username: "tanvir hayder",
    },
    {
        id: 8,
        profilePicture: "person/6.jpg",
        username: "sabrina akter",
    },
    {
        id: 9,
        profilePicture: "person/sabbir.jpg",
        username: "sabbir",
    },
    {
        id: 10,
        profilePicture: "person/rahman.jpg",
        username: "rahman mia",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "fresh from my garden,order now to get at a cheaper price:",
        amount:"200kg",
        photo: "post/1.jpg",
        date: "7 mins ago",
        userId: 1,
        likes: 32,
        Comment: 5,
    },
    {
        id: 2,
        desc: "fresh from my garden,order now to get at a cheaper price:",
        amount:"200kg",
        photo: "post/2.jpg",
        date: "5 hr ago",
        userId: 2,
        likes: 32,
        Comment: 15,
    },
    {
        id: 3,
        desc: "fresh from my garden,order now to get at a cheaper price:",
        amount:"200kg",
        photo: "post/3.jpg",
        date: "8 min ago",
        userId: 3,
        likes: 32,
        Comment: 8,
    },
    {
        id: 4,
        desc: "fresh from my garden,order now to get at a cheaper price:",
        amount:"200kg",
        photo: "post/4.jpg",
        date: "",
        userId: 4,
        likes: 32,
        Comment: 5,
    },
    {
        id: 5,
        desc: "fresh from my garden,order now to get at a cheaper price:",
        amount:"200kg",
        photo:"post/5.jpg",
        date: "",
        userId: 5,
        likes: 32,
        Comment: 5,
    },
    {
        id: 6,
        desc: "fresh from my garden,order now to get at a cheaper price:",
        amount:"200kg",
        photo: "post/6.jpg",
        date: "",
        userId: 6,
        likes: 32,
        Comment: 5,
    },
    {
        id: 7,
        desc: "fresh from my garden,order now to get at a cheaper price:",
        amount:"200kg",
        photo: "post/4.jpg",
        date: "16 min ago",
        userId: 7,
        likes: 32,
        Comment: 5,
    },
    {
        id: 10,
        desc: "fresh from my garden,order now to get at a cheaper price:",
        amount:"200kg",
        photo: "post/10.png",
        date: "16 min ago",
        userId: 10,
        likes: 32,
        Comment: 5,
    },
    {
        id: 8,
        desc: "fresh from my garden,order now to get at a cheaper price:",
        amount:"200kg",
        photo: "post/8.jpeg",
        date: "16 min ago",
        userId: 8,
        likes: 32,
        Comment: 5,
    },
    {
        id: 9,
        desc: "fresh from my garden,order now to get at a cheaper price:",
        amount:"200kg",
        photo: "post/9.jpeg",
        date: "16 min ago",
        userId: 9,
        likes: 32,
        Comment: 5,
    },
]